### ISSUE TITLE
Normalize casing of IAM actions

### ISSUE THREAD

**Issue by mhart** [aws/serverless-application-model#1592]
As I was debugging some permissions issues with one of my stacks, I noticed that the generated permissions sometimes had different casing/capitalization. It didn't take me too long to eliminate this as a cause of the issues I was seeing, but it still took me a bit of Googling to confirm.

Just for the sake of consistency, and so that no one else ends up debugging issues like this, it would be great to have the same casing over all permissions (and I think PascalCase seems to be the dominant standard here)

Here's an example of inconsistent casing (`sns:publish` here vs `sns:Publish` elsewhere), but there may be more:

https://github.com/awslabs/serverless-application-model/blob/37804045790dfa38a93e690e96e718b1d94e6dc9/samtranslator/model/iam.py#L71

**Comment by aahung** [comment]
Trivial fix: #2148

**Comment by jfuss** [comment]
Left a comment https://github.com/aws/serverless-application-model/pull/2148#issuecomment-1081191496 but adding here as well.

The PR was closed due to the understanding this will cause redeployments for customer stacks. Redeployments have caused multiple issue for SAM in the past and we consider changes that do this breaking changes.

While we should remain consistent, we can't change the current policies without negatively impacting customers. Given that, going to close this issue as well. If I am misunderstanding how this is handled between IAM and CloudFormation, happy to re-look at this.

Closing
