### ISSUE TITLE
Common Docker Image

### ISSUE THREAD

**Issue by skwashd** [aws/serverless-application-model#1881]
I have been playing with the new docker support in Lambda. I have a feature request.

I would like to build event driven SAM apps where I have a common docker image that contains all of the dependencies and some shared logic for interacting with a third party service. Then each of my lambda functions would have any additional code, the event handler and a docker files with `FROM common_image` (or a variable that replaces the name at build time).

In my mind `template.yaml` would support a common docker image resource that is somewhat similar to `AWS::Serverless::LayerVersion`. First off the common image would be built followed by the each of the docker based lambda functions.

I know I could use `AWS::Serverless::LayerVersion` but docker images allow us to have greater control over what goes into the lambda execution environment.

**Comment by singledigit** [comment]
In reading this (past characters allowed in Tweets :) ), this is currently possible by building the base image and referring to it in the docker file. Where SAM would come in is if you wanted the base image to be part of the current application and have it updated in the same build process as the dependant Lambda functions. It would require SAM to build and push the base image prior to building the dependant images.

**Comment by skwashd** [comment]
I agree on it being a feature request. To avoid confusion, I would like the build process to create the base image defined in the template.

**Comment by jfuss** [comment]
@skwashd Thanks for the feature request but you can do this today. SAM CLI doesn't create a base image because a single image is produced for a function. You can solve this in two manners today: 
1) Use Multi Stage builds in a single dockerfile: https://docs.docker.com/develop/develop-images/multistage-build/
2) Build this 'common' image before invoking `sam build` (can wrap in a `Makefile`) and do a `From` that image in the function specific one. 

If there is something I am miss understand, can you please create the request in https://github.com/aws/aws-sam-cli/issues with a proposal of what you want and how you imagine it working?

Closing as this is doable within SAM today and SAM CLI is meant to build a single artifact for a given resource.
