### ISSUE TITLE
aws-sam-cli Python requirements from requirements.txt are missing from the deployed Lambda when using a custom template.yaml

### ISSUE THREAD

**Issue by 1-fares** [aws/serverless-application-model#1927]
### Description:

When using -t with a custom template file name, the requirements.txt file seems to be ignored by "sam deploy" (but is respected by "sam build").

### Steps to reproduce:

0. Do a sam init and create a Hello World Python Zip project
1. Import pymysql in your lambda
2. Add "pymysql" to the end of the lambda's requirements.txt
3. Rename template.yaml to custom-template.yaml
4. Build and deploy using "sam build -t custom-template.yaml && sam deploy -t custom-template.yaml"
5. Run your lambda function and/or inspect the lambda function in the AWS console 

### Observed result:

The pymysql requirement is present in the .aws-sam/build/HelloWorldFunction/ directory, but it is missing from the actual deployed lambda:

- Running the lambda results in an exception complaining about a missing pymysql import
- Looking at the directory contents in the AWS console shows no included required libraries

If running with the default template file name "template.yaml" and no "-t" option, then the problem does not appear and the libraries appear to be included correctly.

### Expected result:

- Running the lambda works without exceptions
- The requirements (eg. pymysql and PyMySQL-1.0.2.dist-info) are present when checking the lambda in the AWS console.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04.02 LTS
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.18.1
3. AWS region: eu-west-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by jfuss** [comment]
@1-fares This is an issue with how you are using the commands. Instead of `sam build -t custom-template.yaml && sam deploy -t custom-template.yaml`, you will want to do `sam build -t custom-template.yaml && sam deploy`.

What you are doing is telling `sam deploy` to use the "source template" which points to non-built functions. Instead, if you drop the `-t` from the `sam deploy` command, SAM CLI will pick up the built template from `.aws-sam/build/template.yaml` which will have all the dependencies "installed".

Closing as this is expected behavior and the solution is not to tell `sam deploy` to use the "source template".

**Comment by 1-fares** [comment]
Yes indeed, that was it, thanks!

What was especially confusing was the symptoms, with everything working with "deploy -t": the function code was zipped and uploaded, all CloudFormation resources were created - _except_ for the dependencies in requirements.txt that were missing in the deployed functions.
