### ISSUE TITLE
Link to examples links to an archived repository

### ISSUE THREAD

**Issue by NickDarvey** [aws/serverless-application-model#1992]
The examples folder in this repo has a [README.md](https://github.com/aws/serverless-application-model/blob/develop/examples/apps/README.md) which points to [a repo](https://github.com/amazon-archives/serverless-app-examples) that is now archived.

Where are the current examples? Can the link be updated?

**Comment by jfuss** [comment]
Those are the current examples. Further examples can be found by going through SAM CLI's `init` command. If there are specific examples or starters that will be helpful, we are happy to expand our examples (which are located here: https://github.com/aws/aws-sam-cli-app-templates).

The link to the archive repo is still accurate but the repo is not maintained actively and therefore was archived. Maybe the better thing to do is link out to SAM CLI `init` instead of the example repo or maybe https://serverlessland.com/patterns is more helpful? Thoughts @NickDarvey

**Comment by hoffa** [comment]
Fixed in https://github.com/aws/serverless-application-model/pull/2277.
