### ISSUE TITLE
Cannot set 'Access-Control-Expose-Headers' CORS setting

### ISSUE THREAD

**Issue by singledigit** [aws/serverless-application-model#2084]
### Description:
SAM only supports CORS configuration on API Gateway REST APIs for 

```
  AllowCredentials: Boolean
  AllowHeaders: String
  AllowMethods: String
  AllowOrigin: String
  MaxAge: String
```

We need the ability to set 
```
Access-Control-Expose-Headers: String
```

See: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html

**Comment by chrisoverzero** [comment]
The CORS headers which can be specified in SAM are those which are which are included in a _preflight_ response. The application has to include some CORS headers in its response, as well, because API Gateway cannot modify the response which flows through it (in the way in which Lambda is integrated). `Access-Control-Expose-Headers` is a header which is included in an "actual" response.

Personally, I've always found this chart helpful for remembering what headers belong to what parts of the CORS lifecycle. Note, for example, that `Access-Control-Allow-Origin` is a header for both kinds of request.

![](https://i.stack.imgur.com/urKmt.png)

**Comment by CoshUS** [comment]
For `AWS::Serverless::HttpApi` / `AWS::ApiGatewayV2::Api`, `Access-Control-Expose-Headers` is supported out of the box with the CorsConfiguration [SAM](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-httpapi-httpapicorsconfiguration.html#sam-httpapi-httpapicorsconfiguration-exposeheaders), [APIGWV2](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-api-cors.html#cfn-apigatewayv2-api-cors-exposeheaders).  However, for `AWS::Serverless::Api`, due to the limitations of `AWS::ApiGateway::RestApi`, headers added for the actual responses instead of [pre-flight ones](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html) need to be added in the [integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-integration-settings-integration-response.html).
