### ISSUE TITLE
Deleting a bucket policy fails and also removes all access to the bucket

### ISSUE THREAD

**Issue by GregSommerville** [aws/serverless-application-model#2114]
### Description:
I have a SAM template that creates a bucket.  I added a bucket policy to it that denied access to all except for a VPC.  That worked fine, but then I removed the policy from the template.  When I did a `sam deploy`, the deletion of that policy failed due to a lack of permissions, and now the bucket is completely inaccessible.

**Comment by jfuss** [comment]
@GregSommerville Unfortunately, this isn't something we can help with. We only translate the SAM Spec to CloudFormation. Once that is done, SAM's responsibilities are over. I don't think CloudFormation would be help either, since this is a policy restriction on the bucket but S3 should be able to. Your path forward here would be to reach out through AWS Support or you Account rep to help either remove the bucket or get the Policy to a place you can do what you need to.

Closing as this isn't actionable by SAM
