### ISSUE TITLE
[Feature Request] Politely asking for an increase of lambda layer max size

### ISSUE THREAD

**Issue by allanchua101** [aws/serverless-application-model#2196]
### Describe your idea/feature/enhancement

When working on ML projects that involve libraries like:

 - Numpy
 - Spacy
 - Pandas
 - Scikit Learn & Scikit Learn Image
 - OpenCV
 - PyTorch
 - Tensorflow
 - MTCNN

We often need dependencies that exceed the maximum size supported by AWS lambda. Tensorflow lite was introduced because the raw tensorflow library requires 1GB of dependencies even without the other supporting libraries like Numpy and scikit learn images. I know we can get around this by compressing the Tensorflow models into their TF Lite versions but some frameworks are not as good as them eg. MTCNN (State of the art facial detection library as of 2021). 

### Proposal

In my humble opinion, serverless and lambda would be adopted by more data scientists and ml engineers if AWS enables them by providing a way to easily mount custom ML models in lambda functions. I can see two ways where we can enable them:

1). A quick fix here would be "Increase the **MAXIMUM** size of lambda layers from **250MB** to **2GB**"
2). An even better approach at least from my perspective is for AWS to provide a marketplace of lambda layers where they can easily acquire/depend on top of common lambda layer compositions that include popular ML libraries  (Tensorflow, OpenCV, PyTorch)  as a base layer for their functions/layers.

### Additional Details

I know Docker and EFS solutions can help in getting rid of maximum size limitations of layers but please do consider that not all data science teams are familiar with these AWS concepts which results to them being hesitant to build POCs on top of this wonderful and efficient technology.

**Comment by jfuss** [comment]
@allanchua101 Thanks for reaching out. However, this is not something we can directly help with. SAM's Spec is based on the restrictions of Lambda (in the number of layers and the size restrictions of Lambda). I don't have any additional work around than you mentioned (using Lambda Images or EFS). 

I will pass this along to the service team. You can also try reaching out to AWS Support, as an alternative.

Since there is not any action we can take, I am going to close this issue.
