### ISSUE TITLE
Warning on metric publishing not needed in all scenarios

### ISSUE THREAD

**Issue by kddejong** [aws/serverless-application-model#2206]
I don't believe there should be a warning if the user is using `DummyMetricsPublisher`

https://github.com/aws/serverless-application-model/blob/560cc8cae3753e044e7a297443fafba1925b8d79/samtranslator/metrics/metrics.py#L128

https://github.com/aws-cloudformation/cfn-lint/issues/2167

**Comment by amancevice** [comment]
this is causing an intrusive error to pop on on every save with the Atom cfn-lint plugin

**Comment by jfuss** [comment]
@kddejong Do you really want logs from dependencies? If not cfn lint could control the logger namespace and make `samtransform` logs not emit. We should probably do this by default in the lib and only enable in the SAM service. 

I say this because it gives you a way to patch now, though we should fix this.

**Comment by kddejong** [comment]
Let me see if I can handle that on my side.  Thanks @jfuss

**Comment by kddejong** [comment]
@jfuss I'm releasing a version of `cfn-lint` now with a modified logging level.  I'll leave it to you if you want to leave this open or not.

**Comment by amancevice** [comment]
The new version resolved my issue with the cfn-lint Atom plugin

**Comment by moelasmar** [comment]
Thanks @kddejong for your contribution. 
I am closing this issue based on your contribution, please feel free to reopen the issue if you have any questions.
