### ISSUE TITLE
DeletionPolicy support for AWS SAM function and layer

### ISSUE THREAD

**Issue by jchirschy** [aws/serverless-application-model#2212]
Hello,

Please add support for `DeletionPolicy` property for `AWS::Serverless::Function` and `AWS::Serverless::LayerVersion` and ability to specify it as `Globals`.

Thanks

**Comment by jfuss** [comment]
`DeletionPolicy` is supported but it is not a property and instead can be defined following CloudFormation's format. https://github.com/aws/serverless-application-model/blob/90edf3e1304f79bb5da12860e6fe6e6c776ff5a5/tests/translator/input/implicit_api_deletion_policy_precedence.yaml#L4 is an example from our tests. You can do the same thing for `AWS::Serverless::LayerVersion`, though we do support a property for that resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-layerversion.html#sam-layerversion-retentionpolicy. We prefer to follow CloudFormation rather than create specific properties for each resource.

Closing as this is already supported and prefer to follow CloudFormation's languages than creating specific properties and adding them to Globals.
